import os
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

# Correct namespaced imports for google-adk
from google.adk.agents import Agent
from google.adk.tools import AgentTool
from google.adk.agents import SequentialAgent

app = FastAPI(title="Research Agent Web Service")

# --- 1. Define Specialized Agents ---
researcher = Agent(
    name="Researcher",
    instruction="We gather raw technical data and market facts.",
    model="gemini-2.0-flash"
)

synthesizer = Agent(
    name="Synthesizer",
    instruction="We transform raw data into professional executive reports.",
    model="gemini-2.0-flash"
)

# --- 2. Sequential Multi-Agent Orchestration ---
# This 'root_agent' is what ADK Web and CLI tools look for by default
root_agent = SequentialAgent(
    name="ResearchPipeline",
    sub_agents=[researcher, synthesizer]
)

# --- 3. FastAPI Endpoints for Render ---
class ResearchRequest(BaseModel):
    topic: str

@app.get("/")
def health_check():
    return {"status": "ADK Web Enabled", "active": True}

@app.post("/research")
async def run_pipeline(request: ResearchRequest):
    try:
        final_text = ""
        
        # Iterate through the async generator from the SequentialAgent
        async for event in root_agent.run_async(request.topic):
            # Check for the text attribute in the event object
            if hasattr(event, 'text') and event.text:
                final_text = event.text
            elif hasattr(event, 'content') and hasattr(event.content, 'parts'):
                final_text = event.content.parts[0].text
        
        if not final_text:
            # Fallback if the loop finishes without finding specific text
            final_text = "No report was generated by the agents."

        # CRITICAL FIX: Return a plain dict to avoid Pydantic's .model_copy() crash
        return {"status": "success", "report": str(final_text)}
        
    except Exception as e:
        # Logging the error to Render console for visibility
        print(f"Detailed Pipeline Error: {e}")
        # Return a dictionary even for errors
        return {"status": "error", "detail": str(e)}
        
if __name__ == "__main__":
    import uvicorn
    # Bind to Render's dynamic port
    port = int(os.environ.get("PORT", 8000))
    uvicorn.run(app, host="0.0.0.0", port=port)
